version:  '3.2'
services:
  nginx:
    image: nginx:1.13.3
#    image: nginx
    ports:
      - "80:80"
    links:
      - "php-fpm:php-fpm"
    volumes:
      - ./app:/app:rw
      - ./dockerfiles/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./dockerfiles/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./logs/nginx:/var/log/nginx
      - /etc/localtime:/etc/localtime:ro
    restart: always
    command: nginx -g 'daemon off;'

  mysql-db:
    image: mysql:5.7
    volumes:
      - ./data/mysql:/var/lib/mysql:rw
      - ./logs/mysql:/var/lib/mysql-logs:rw
      - ./dockerfiles/mysql/conf.d:/etc/mysql/conf.d:ro
      - /etc/localtime:/etc/localtime:ro
    restart: always
    ports:
      - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: zhaojun
        MYSQL_DATABASE: package_v1
        MYSQL_USER: zhaojun
        MYSQL_PASSWORD: zhaojun
    command: "--character-set-server=utf8 --collation-server=utf8_unicode_ci"

  redis-db:
    build: ./dockerfiles/redis
    restart: always
    volumes:
      - ./data/redis:/data
      - /etc/localtime:/etc/localtime:ro

  php-fpm:
    build: ./dockerfiles/php/
    #image: zhaojunlike/php-fpm:5.6-latest
    restart: always
    environment:
      TP_APP_DEBUG: 1
      APP_DEBUG: 1
    volumes:
      - ./app:/app:rw
      - ./dockerfiles/php/php-dev.ini:/usr/local/etc/php/php.ini:ro
      - ./dockerfiles/php/php-fpm.conf:/usr/local/etc/php-fpm.conf:ro
      - /etc/localtime:/etc/localtime:ro
      - ./logs/php-fpm:/var/log/php-fpm:rw
    links:
      - mysql-db:mysql-db
      - redis-db:redis-db
    command: php-fpm
    ports:
      - "9000:9000"
      
##附加扩展安装器
##composer构建工具，官方的composer中得php未编译bcmath
  composer:
    #image: composer:1.4.2
    image: zhaojunlike/composer:5.6-latest
    #build: ./dockerfiles/composer/
    volumes:
    #网站目录
      - ./app:/app:rw
    working_dir: /app/webroot
    command: composer install

  bower:
    image: digitallyseamless/nodejs-bower-grunt
    volumes:
      - ./app:/app:rw
    working_dir: /app/webroot
    deploy:
      restart_policy:
        condition: none
    command: bower install

